name: data-science-cop
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - ipywidgets
  - ipykernel
  - numpy
  - pandas
  - xarray
  - iris
  - proj4=5
  - mo_pack
  - netcdftime
  - matplotlib
  - cartopy
  - bokeh
  - scikit-learn
  - pip